### ISSUE TITLE
Unsupported release: 14.04 Ubuntu 

### ISSUE THREAD

**Issue by yongololo** [posm/OpenMapKitServer#119]
I'm trying to install POSM on Ubuntu 14.04 LTS but I get the error message that the version does not support what to do ?

**Comment by danbjoseph** [comment]
can you take a picture of the error message and post here?
are you using the install instructions found here: http://posm.io/getting-a-posm/ ?

**Comment by mojodna** [comment]
@yongololo POSM now requires Ubuntu 18.04 LTS when installing from source. We'll be publishing a release shortly with new installers.
